version: "3.3"
services:
  jenkins:
      build:
        context: .
      ports:
        - "8080:8080"
      #user: "jenkins:jenkins"  
      volumes:
        - "../app/.git:/tmp/rep"
        - "/var/run/docker.sock:/var/run/docker.sock"
